"""add priority field to task model

Revision ID: 0a228475fdd1
Revises: a1c5bc8af11e
Create Date: 2026-03-26 16:08:13.647301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a228475fdd1'
down_revision: Union[str, Sequence[str], None] = 'a1c5bc8af11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='taskpriority'), server_default='medium', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
