"""add is_recurring in task models

Revision ID: 439c590c32e3
Revises: 787661ed1ff6
Create Date: 2026-03-26 18:17:45.734851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439c590c32e3'
down_revision: Union[str, Sequence[str], None] = '787661ed1ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('repeat_every_days', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'next_run_at')
    op.drop_column('tasks', 'repeat_every_days')
    op.drop_column('tasks', 'is_recurring')
    # ### end Alembic commands ###
