"""add deadline_reminder_sent_at

Revision ID: 45dff8e58e45
Revises: 439c590c32e3
Create Date: 2026-03-26 18:32:28.182175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45dff8e58e45'
down_revision: Union[str, Sequence[str], None] = '439c590c32e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline_reminder_sent_at')
    # ### end Alembic commands ###
